# Dockerfile.dev
FROM golang:1.22-alpine

WORKDIR /app

# Install necessary tools
RUN apk add --no-cache git curl bash air

# Copy go mod first for layer caching
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Copy source
COPY . .

CMD ["air"]
